<?php
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../config/auth.php';
require_once __DIR__ . '/../config/payment.php';
require_admin();
$year=(int)($_GET['year']??date('Y')); $year=max(2020,min(date('Y'),$year));
$sql="SELECT MONTH(date) month,COALESCE(SUM(student_count*?),0) revenue,COALESCE(SUM(CASE WHEN payment_status='paid' THEN student_count*? ELSE 0 END),0) paid,COUNT(*) lessons FROM timetable WHERE deleted_at IS NULL AND YEAR(date)=? GROUP BY MONTH(date) ORDER BY month";
$stmt=$pdo->prepare($sql);$stmt->execute([$FEE_PER_STUDENT_LIVE,$FEE_PER_STUDENT_LIVE,$year]);$rows=$stmt->fetchAll();$months=array_fill(1,12,['revenue'=>0,'paid'=>0,'lessons'=>0]);foreach($rows as $r)$months[(int)$r['month']]=['revenue'=>(float)$r['revenue'],'paid'=>(float)$r['paid'],'lessons'=>(int)$r['lessons']];
$total=array_sum(array_column($months,'revenue'));$paid=array_sum(array_column($months,'paid'));$pending=$total-$paid;$lessons=array_sum(array_column($months,'lessons'));$activeMonths=count(array_filter($months,fn($m)=>$m['revenue']>0));
include __DIR__ . '/../includes/header.php';
?>
<div class="finance-page"><div class="finance-heading"><div><h1><i class="bi bi-calendar3"></i> Yearly Revenue</h1><p><?=$year?> revenue trend and payment collection.</p></div><div class="finance-actions"><a class="btn btn-outline-primary" href="monthly.php">Monthly report</a><a class="btn btn-primary" href="../timetable/export_csv.php?type=timetable&date_from=<?=$year?>-01-01&date_to=<?=$year?>-12-31"><i class="bi bi-download"></i> Export</a></div></div>
<div class="finance-toolbar"><form class="row g-3 align-items-end"><div class="col-md-4"><label class="form-label">Year</label><select class="form-select" name="year"><?php for($y=date('Y')-3;$y<=date('Y');$y++):?><option value="<?=$y?>" <?=$y===$year?'selected':''?>><?=$y?></option><?php endfor;?></select></div><div class="col-md-8 d-flex gap-2"><button class="btn btn-primary flex-fill">Update</button><a class="btn btn-outline-secondary" href="yearly.php">Current year</a></div></form></div>
<div class="finance-stat-grid"><article class="finance-stat"><span class="label">Annual revenue</span><span class="value"><?=htmlspecialchars($CURRENCY_SYMBOL_LIVE)?> <?=number_format($total)?></span><span class="meta"><?=number_format($lessons)?> lessons</span></article><article class="finance-stat"><span class="label">Paid</span><span class="value text-success"><?=htmlspecialchars($CURRENCY_SYMBOL_LIVE)?> <?=number_format($paid)?></span><span class="meta"><?= $total>0?round($paid/$total*100,1):0 ?>% collected</span></article><article class="finance-stat"><span class="label">Pending</span><span class="value text-warning-emphasis"><?=htmlspecialchars($CURRENCY_SYMBOL_LIVE)?> <?=number_format($pending)?></span><span class="meta">Outstanding</span></article><article class="finance-stat"><span class="label">Active months</span><span class="value"><?=$activeMonths?></span><span class="meta">With recorded revenue</span></article></div>
<div class="finance-panel"><div class="finance-panel-header"><h2>Monthly trend</h2></div><div class="finance-panel-body"><div class="chart-shell"><canvas id="yearlyChart"></canvas></div></div></div>
</div><script src="https://cdn.jsdelivr.net/npm/chart.js"></script><script>new Chart(document.getElementById('yearlyChart'),{type:'bar',data:{labels:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],datasets:[{label:'Revenue',data:<?=json_encode(array_column($months,'revenue'))?>},{label:'Paid',data:<?=json_encode(array_column($months,'paid'))?>}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:'top'}},scales:{y:{beginAtZero:true}}}});</script><?php include __DIR__ . '/../includes/footer.php'; ?>
