-- Temporary third-device access for one live class. This does not raise the 2-device limit.
CREATE TABLE IF NOT EXISTS emergency_device_requests (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    student_name VARCHAR(160) NOT NULL DEFAULT '',
    device_key CHAR(64) NOT NULL,
    device_label VARCHAR(120) NOT NULL DEFAULT '',
    timetable_id INT NOT NULL,
    meeting_id INT NULL,
    lesson_teacher_id INT NOT NULL DEFAULT 0,
    substitute_teacher_id INT NOT NULL DEFAULT 0,
    class_label VARCHAR(160) NOT NULL DEFAULT '',
    teacher_name VARCHAR(160) NOT NULL DEFAULT '',
    lesson_date DATE NULL,
    end_time VARCHAR(16) NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    reason VARCHAR(255) NULL,
    requested_at DATETIME NOT NULL,
    expires_at DATETIME NOT NULL,
    decided_at DATETIME NULL,
    decided_by_user_id INT NULL,
    decided_by_role VARCHAR(32) NULL,
    decided_by_name VARCHAR(160) NULL,
    access_until DATETIME NULL,
    ip_address VARCHAR(45) NULL,
    pending_key CHAR(64) NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_emergency_device_pending (pending_key),
    KEY idx_emergency_device_user (user_id, timetable_id, status),
    KEY idx_emergency_device_teacher (lesson_teacher_id, status, expires_at),
    KEY idx_emergency_device_status (status, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
