<?php
require_once __DIR__ . '/../config/database.php';
require_once __DIR__ . '/../config/auth.php';
require_admin();

$error = '';
$success = '';

// Handle backup download
if (isset($_GET['download'])) {
    $format = $_GET['format'] ?? 'sql';
    $tables = [];
    $result = $pdo->query("SHOW TABLES");
    while ($row = $result->fetch(PDO::FETCH_NUM)) {
        $tables[] = $row[0];
    }
    
    if ($format === 'sql') {
        header('Content-Type: application/sql');
        header('Content-Disposition: attachment; filename="backup_' . date('Y-m-d_H-i-s') . '.sql"');
        echo "-- Edexcel College Database Backup\n";
        echo "-- Generated: " . date('Y-m-d H:i:s') . "\n\n";
        
        foreach ($tables as $table) {
            echo "-- Table: $table\n";
            $stmt = $pdo->query("SHOW CREATE TABLE $table");
            $create = $stmt->fetch(PDO::FETCH_ASSOC);
            echo $create['Create Table'] . ";\n\n";
            
            $data = $pdo->query("SELECT * FROM $table");
            while ($row = $data->fetch(PDO::FETCH_ASSOC)) {
                $cols = array_keys($row);
                $values = array_map(function($v) use ($pdo) {
                    if ($v === null) return 'NULL';
                    return $pdo->quote($v);
                }, $row);
                echo "INSERT INTO $table (" . implode(', ', $cols) . ") VALUES (" . implode(', ', $values) . ");\n";
            }
            echo "\n";
        }
        log_audit($pdo, 'backup_download', 'system');
        exit();
    }
}

// Handle restore (upload SQL file)
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['restore'])) {
    $csrf_token = $_POST['csrf_token'] ?? '';
    if (!verify_csrf_token($csrf_token)) {
        $error = 'Invalid security token.';
    } elseif (
        isset($_FILES['sql_file']) &&
        $_FILES['sql_file']['error'] === UPLOAD_ERR_OK
    ) {
        $upload = $_FILES['sql_file'];

        if ((int)$upload['size'] > 25 * 1024 * 1024) {
            $error = 'Backup file is too large. Maximum size is 25 MB.';
        } elseif (
            !is_uploaded_file($upload['tmp_name']) ||
            !preg_match('/\.sql$/i', (string)$upload['name'])
        ) {
            $error = 'Please upload a valid .sql backup file.';
        }

        $file = $upload['tmp_name'];
        $content = isset($error) && $error !== '' ? false : file_get_contents($file);
        if ($content === false) {
            $error = 'Failed to read file.';
        } else {
            try {
                // Reject obviously dangerous server/file-level commands.
                if (preg_match('/(^|\R)\s*(?:SOURCE|LOAD\s+DATA|\\!|SYSTEM)\\b/i', $content)) {
                    throw new RuntimeException('The backup contains unsupported server-level commands.');
                }

                // The application restore format is generated by this page:
                // CREATE TABLE and INSERT statements only.
                $statements = array_values(array_filter(
                    array_map('trim', preg_split('/;\\s*(?:\\R|$)/', $content))
                ));

                if (!$statements || count($statements) > 100000) {
                    throw new RuntimeException('The backup file is invalid or contains too many statements.');
                }

                $pdo->beginTransaction();
                foreach ($statements as $stmt) {
                    if (!preg_match('/^(?:--[^\\n]*\\n\\s*)*(?:CREATE\\s+TABLE|INSERT\\s+INTO|SET\\s+)/is', $stmt)) {
                        throw new RuntimeException('Unsupported SQL statement found in backup.');
                    }
                    $pdo->exec($stmt);
                }
                $pdo->commit();
                log_audit($pdo, 'restore_database', 'system');
                $success = 'Database restored successfully from SQL file.';
            } catch (Throwable $e) {
                if ($pdo->inTransaction()) {
                    $pdo->rollBack();
                }
                error_log('Database restore failed: ' . $e->getMessage());
                $error = 'Restore failed. Please verify that the backup was generated by this application.';
            }
        }
    } else {
        $error = 'Please upload a valid SQL file.';
    }
}

include __DIR__ . '/../includes/header.php';
?>
<h1><i class="bi bi-database"></i> Database Backup & Restore</h1>

<?php if ($success): ?>
    <div class="alert alert-success"><?= htmlspecialchars($success) ?></div>
<?php endif; ?>
<?php if ($error): ?>
    <div class="alert alert-danger"><?= htmlspecialchars($error) ?></div>
<?php endif; ?>

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header bg-primary text-white">
                <i class="bi bi-download"></i> Backup
            </div>
            <div class="card-body">
                <p>Download a full SQL backup of your database.</p>
                <a href="backup.php?download=1&format=sql" class="btn btn-success">
                    <i class="bi bi-file-earmark-zip"></i> Download SQL Backup
                </a>
                <small class="d-block text-muted mt-2">Backup includes all tables and data.</small>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card">
            <div class="card-header bg-warning text-dark">
                <i class="bi bi-upload"></i> Restore
            </div>
            <div class="card-body">
                <p><strong>Warning:</strong> This will overwrite all current data!</p>
                <form method="POST" enctype="multipart/form-data">
                    <?= csrf_field() ?>
                    <div class="mb-3">
                        <label for="sql_file" class="form-label">Select SQL file</label>
                        <input type="file" class="form-control" id="sql_file" name="sql_file" accept=".sql" required>
                    </div>
                    <button type="submit" name="restore" class="btn btn-danger" onclick="return confirm('Are you sure you want to restore this backup? All current data will be replaced.')">
                        <i class="bi bi-arrow-counterclockwise"></i> Restore
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="mt-4">
    <h4>Current Tables</h4>
    <div class="table-responsive">
        <table class="table table-sm">
            <thead>
                <tr>
                    <th>Table</th>
                    <th>Rows</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $result = $pdo->query("SHOW TABLES");
                while ($row = $result->fetch(PDO::FETCH_NUM)) {
                    $table = $row[0];
                    $count = $pdo->query("SELECT COUNT(*) FROM $table")->fetchColumn();
                    echo "<tr><td>$table</td><td>" . number_format($count) . "</td></tr>";
                }
                ?>
            </tbody>
        </table>
    </div>
</div>
<?php include __DIR__ . '/../includes/footer.php'; ?>