<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/bootstrap.php';
require_once __DIR__ . '/../vendor/autoload.php';
use Edexcel\Services\StudentRiskService;
require_admin();$svc=new StudentRiskService($pdo);$error='';$success='';
if($_SERVER['REQUEST_METHOD']==='POST'){if(!verify_csrf_token($_POST['csrf_token']??''))$error='Security token expired.';else try{$svc->createIntervention($_POST,(int)$_SESSION['user_id']);$success='Intervention created and audited.';}catch(Throwable $e){$error=$e->getMessage();}}
$level=$_GET['level']??null;$rows=$svc->dashboard($level);$all=$svc->dashboard();$counts=array_count_values(array_column($all,'risk_level'));
include __DIR__ . '/../includes/header.php';?>
<div class="container-fluid py-4"><h1 class="h3"><i class="bi bi-shield-exclamation"></i> Student risk &amp; early warning</h1><p class="text-muted">Deterministic, configurable scoring from attendance, marks, homework and outstanding fees.</p><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><?php if($success):?><div class="alert alert-success"><?=e($success)?></div><?php endif;?><div class="row g-2 mb-3"><?php foreach(['LOW','MEDIUM','HIGH','CRITICAL'] as $l):?><div class="col-6 col-lg-3"><a class="card border-0 shadow-sm p-3 text-decoration-none" href="?level=<?=$l?>"><div class="small text-muted"><?=$l?></div><div class="fs-3 fw-bold"><?= (int)($counts[$l]??0)?></div></a></div><?php endforeach;?></div><div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Student</th><th>Level</th><th>Score</th><th>Attendance</th><th>Academic</th><th>Homework</th><th>Reasons</th><th></th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['username'])?></td><td><span class="badge text-bg-<?=$r['risk_level']==='LOW'?'success':'danger'?>"><?=e($r['risk_level'])?></span></td><td><?=e((string)$r['risk_score'])?></td><td><?=e((string)($r['attendance_percent']??'—'))?>%</td><td><?=e((string)($r['academic_percent']??'—'))?>%</td><td><?=e((string)($r['homework_percent']??'—'))?>%</td><td class="small"><?php foreach($r['reasons'] as $reason):?><div><?=e($reason)?></div><?php endforeach;?></td><td><a class="btn btn-sm btn-outline-primary" href="student360.php?student=<?= (int)$r['student_id']?>">360°</a></td></tr><?php endforeach;?></tbody></table></div></div></div><?php include __DIR__ . '/../includes/footer.php';?>
