<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/bootstrap.php';
require_admin();$error='';$success='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verify_csrf_token($_POST['csrf_token']??''))$error='Security token expired.';
 else try{$report=(string)$_POST['report_key'];$frequency=(string)$_POST['frequency'];$recipients=array_values(array_filter(array_map('trim',explode(',',(string)$_POST['recipients']))));if(!in_array($report,['daily_collection','attendance','monthly_income','teacher_payments','outstanding_fees','exam_preparation'],true))throw new RuntimeException('Unsupported report.');if(!in_array($frequency,['daily','weekly','monthly'],true)||$recipients===[])throw new RuntimeException('Choose a frequency and recipient.');$pdo->prepare("INSERT INTO scheduled_reports(report_key,frequency,recipients_json,channel,active,next_run_at,created_by) VALUES(?,?,?,'in_app',1,NOW(),?)")->execute([$report,$frequency,json_encode($recipients),(int)$_SESSION['user_id']]);$success='Report schedule saved.';}catch(Throwable $e){$error=$e->getMessage();}
}
$rows=$pdo->query('SELECT * FROM scheduled_reports ORDER BY id DESC')->fetchAll(PDO::FETCH_ASSOC)?:[];include __DIR__ . '/../includes/header.php';?>
<div class="container-fluid py-4"><h1 class="h3"><i class="bi bi-clock-history"></i> Scheduled reports</h1><p class="text-muted">Reports are queued through existing jobs; recipient addresses are stored as configuration, not credentials.</p><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><?php if($success):?><div class="alert alert-success"><?=e($success)?></div><?php endif;?><div class="row g-4"><div class="col-lg-5"><form method="post" class="card shadow-sm border-0 p-3"><?=csrf_field()?><label class="form-label">Report</label><select class="form-select mb-2" name="report_key"><?php foreach(['daily_collection','attendance','monthly_income','teacher_payments','outstanding_fees','exam_preparation'] as $r):?><option><?=$r?></option><?php endforeach;?></select><label class="form-label">Frequency</label><select class="form-select mb-2" name="frequency"><option>daily</option><option>weekly</option><option>monthly</option></select><label class="form-label">Recipients (comma-separated)</label><input class="form-control mb-3" name="recipients" required><button class="btn btn-primary">Schedule report</button></form></div><div class="col-lg-7"><div class="card shadow-sm border-0 p-3"><h2 class="h5">Schedules</h2><?php foreach($rows as $r):?><div class="border-bottom py-2 d-flex justify-content-between"><span><?=e($r['report_key'])?> · <?=e($r['frequency'])?></span><small><?=e((string)$r['next_run_at'])?></small></div><?php endforeach;?></div></div></div></div><?php include __DIR__ . '/../includes/footer.php';?>
