<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/bootstrap.php';
require_once __DIR__ . '/../vendor/autoload.php';
use Edexcel\Services\TimetableSuggestionService;
require_admin();$suggestions=[];$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){if(!verify_csrf_token($_POST['csrf_token']??''))$error='Session expired.';else try{$suggestions=(new TimetableSuggestionService($pdo))->suggest((int)$_POST['teacher_id'],(int)$_POST['room_id'],(int)$_POST['class_id'],(string)$_POST['date'],(string)$_POST['duration']);}catch(Throwable $e){$error=$e->getMessage();}}
include __DIR__ . '/../includes/header.php';?>
<div class="container py-4"><h1 class="h3">Timetable suggestions</h1><p class="text-muted">Suggestions are approval-only and never change the timetable.</p><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?><form method="post" class="card border-0 shadow-sm p-3 mb-3"><?=csrf_field()?><div class="row g-2"><div class="col-md-3"><input class="form-control" name="teacher_id" type="number" placeholder="Teacher ID" required></div><div class="col-md-3"><input class="form-control" name="class_id" type="number" placeholder="Class ID" required></div><div class="col-md-3"><input class="form-control" name="room_id" type="number" placeholder="Room ID (0 allowed)" required></div><div class="col-md-3"><input class="form-control" name="date" type="date" required></div></div><div class="input-group mt-2"><span class="input-group-text">Duration</span><input class="form-control" name="duration" value="01:00"><button class="btn btn-primary">Find available slots</button></div></form><?php if($suggestions):?><div class="card border-0 shadow-sm"><div class="list-group list-group-flush"><?php foreach($suggestions as $slot):?><div class="list-group-item d-flex justify-content-between"><span><?=e($slot['date'])?> <?=e($slot['start_time'])?>–<?=e($slot['end_time'])?></span><small class="text-muted"><?=e($slot['reason'])?></small></div><?php endforeach;?></div></div><?php endif;?></div><?php include __DIR__ . '/../includes/footer.php';?>
